### PR TITLE
Bump pkgrels to trigger rebuild for python 3.11

### LINKED ISSUE #224: python-pysimplegui: Needs to be rebuilt for python 3.11.
The package `proaudio/python-pysimplegui` needs update. It installs files for python 3.10, but we are at python 3.11:

```
python-pysimplegui /usr/lib/python3.10/
python-pysimplegui /usr/lib/python3.10/site-packages/
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/METADATA
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/RECORD
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/WHEEL
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/entry_points.txt
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI-4.60.4.dist-info/top_level.txt
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__init__.py
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__pycache__/
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__pycache__/PySimpleGUI.cpython-310.opt-1.pyc
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__pycache__/PySimpleGUI.cpython-310.pyc
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__pycache__/__init__.cpython-310.opt-1.pyc
python-pysimplegui /usr/lib/python3.10/site-packages/PySimpleGUI/__pycache__/__init__.cpython-310.pyc
```

Thanks for maintaining!

### PR DESCRIPTION
**Pull request by cbix**
- (except for ola since that takes a long time to build)
- (and qjackcapture since the build failed)
- Closes #224

### CODE REVIEW

**Comment by cbix** [comment]
@SpotlightKid do you see any blockers here? On aarch64 we're still on 3.10 but we'd just update again later

**Comment by SpotlightKid** [comment]
qjackctl?

**Comment by cbix** [comment]
> qjackctl?

*qjackcapture, my mistake :D

**Comment by SpotlightKid** [comment]
python-pyjacklib needs to be rebuilt and the new pkgrel in our repo before qjackcapture can be updated.

**Review by SpotlightKid — APPROVED** [review]

**Pull request merged**
