### PR TITLE
fix: add patch to fix building ola with GCC 14

### PR DESCRIPTION
**Pull request by SpotlightKid**
* Also update license identifiers

Fixes: #448

### CODE REVIEW

**Comment by SpotlightKid** [comment]
> Seems to fail on aarch64 🤔

Yeah, but why?

```
error: Could not create output directory /tmp/build/ola/src/ola-0.10.9/html
make: *** [Makefile:19203: doxygen-doc/ola.tag] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

Could this be a disk space issue?

**Comment by cbix** [comment]
Ah, could be, just ran a `docker system prune` and restarted, thanks 👍

**Comment by SpotlightKid** [comment]
Now we have a test failure on aarch64. Looks like a timing / performance issue.

Should we just exclude the test? There's a dozen test in this one test method, though.

```
...F..

======================================================================

FAIL: testEventLoop (__main__.ClientWrapperTest.testEventLoop)
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/build/ola/src/ola-0.10.9/./python/ola/ClientWrapperTest.py", line 209, in testEventLoop
    self.assertAlmostEqual(d_diff, datetime.timedelta(milliseconds=15),
AssertionError: datetime.timedelta(microseconds=16697) != datetime.timedelta(microseconds=15000) within datetime.timedelta(microseconds=750) delta (datetime.timedelta(microseconds=1697) difference)

----------------------------------------------------------------------
Ran 6 tests in 0.019s

FAILED (failures=1)
FAIL python/ola/ClientWrapperTest.sh (exit status: 1)
```

**Comment by SpotlightKid** [comment]
Could not reproduce the test failure in two further CI runs. The notification step still doesn't work correctly. Not sure why. Need to re-check the authentication token.

Other than that, I think this can be merged.

**Review by cbix — APPROVED** [review]

**Pull request merged**
