### PR TITLE
Respecting freedesktop spec for svg icons

### PR DESCRIPTION
**Pull request by jujudusud**
Updating jamulus package.

Freedesktop spec says that .svg icons have to be in hicolor theme by default instead of pixmap actually.

Ready to be merged.

### CODE REVIEW

**Comment by jujudusud** [comment]
I think it is ok to be merged now.

**Comment by SpotlightKid** [comment]
Shouldn't `hicolor-icon-theme` be added to `depends`?

**Review by SpotlightKid — CHANGES_REQUESTED** [review]
Please add `hicolor-icon-theme` to `depends`.

**Comment by jujudusud** [comment]
> Please add `hicolor-icon-theme` to `depends`.

Added in jamulus package, not in headless.

**Review by SpotlightKid — APPROVED** [review]

**Pull request merged**
